# -*- coding: utf-8 -*-
"""Prak Algo (13)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XtOO7bsyYi0mxz1TQbDV35pNr5yNleVb
"""

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

#list nilai
nilai_siswa = [88,69,74,82,93,46]
#mencari rata-rata
rata_rata = sum(nilai_siswa) / len(nilai_siswa)
print(f"rata-rata niali kelas:, {rata_rata:.1f}")
#Mahasiswa nilai diatas rata-rata
siswa_diatas_rata = [siswa for siswa in nilai_siswa if siswa > rata_rata]
print("siswa yang mendapatkan nilai di atas rata-rata", siswa_diatas_rata)

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

def konversi_mata_uang(jumlah_rupiah, kurs_dolar):
    jumlah_dolar = jumlah_rupiah / kurs_dolar
    return jumlah_dolar

jumlah_rupiah = float (input("masikan jumlah uang dalam rupiah:"))
kurs_dolar = float(input("masukan kurs dolar terhadap rupiah:"))
jumlah_dolar = konversi_mata_uang(jumlah_rupiah, kurs_dolar)
print(f"jumlah uang dalam dolar: ${jumlah_dolar:.2f}")

print('@@@@@      @@         @ @     @    @@@@@      @@@@@        @@     ')
print('@   @     @  @        @   @   @   @          @            @  @    ')
print('@ @      @    @       @     @ @   @   @@@    @   @@@     @    @   ')
print('@  @    @ @@@@ @      @       @   @     @    @     @    @ @@@@ @  ')
print('@   @  @        @     @           @@@@@@@    @@@@@@@   @        @ ')

proyek_list = [
    {"nama": "Proyek A", "status": "Selesai", "estimasi_waktu": 10},
    {"nama": "Proyek B", "status": "Dalam Pengerjaan", "estimasi_waktu": 20},
    {"nama": "Proyek C", "status": "Dalam Pengerjaan", "estimasi_waktu": 15},
    {"nama": "Proyek D", "status": "Selesai", "estimasi_waktu": 8},
]
proyek_dalam_pengerjaan = [proyek for proyek in proyek_list if proyek["status"] == "Dalam Pengerjaan"]

def bubble_sort_proyek(proyek_list):
    n = len(proyek_list)
    for i in range(n - 1):
        for j in range(0, n - i - 1):
            if proyek_list[j]["estimasi_waktu"] > proyek_list[j + 1]["estimasi_waktu"]:
                proyek_list[j], proyek_list[j + 1] = proyek_list[j + 1], proyek_list[j]

print("Proyek yang masih dalam pengerjaan:")
for proyek in proyek_dalam_pengerjaan:
    print(f"Nama: {proyek['nama']}, Estimasi Waktu: {proyek['estimasi_waktu']} hari, Status: {proyek['status']}")

bubble_sort_proyek(proyek_dalam_pengerjaan)

print("\nProyek dalam pengerjaan yang diurutkan berdasarkan estimasi waktu:")
for proyek in proyek_dalam_pengerjaan:
    print(f"Nama: {proyek['nama']}, Estimasi Waktu: {proyek['estimasi_waktu']} hari, Status: {proyek['status']}")